name: Daily Job Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios xlsx cheerio form-data
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Chay Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          MS_TEAMS_WEBHOOK: ${{ secrets.MS_TEAMS_WEBHOOK }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TEAMS_CHANNEL_ID: ${{ secrets.TEAMS_CHANNEL_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_USER_ID: ${{ secrets.AZURE_USER_ID }}
          TEAMS_COOKIES: ${{ secrets.TEAMS_COOKIES }}
        run: node scraper.js

      - name: Upload Excel Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Indeed-Jobs-Excel
          path: Indeed_Jobs.xlsx