name: Daily Job Scraper

on:
  schedule:
    - cron: '0 1 * * *' # Chạy lúc 8h sáng VN
  workflow_dispatch:

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install puppeteer@latest axios@latest
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Chạy Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node scraper.js